
workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Install Dependencies
        script: |
          yarn config set enableImmutableInstalls false
          yarn install
      - name: Clean and Fix Android
        script: |
          cd android
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          chmod +x gradlew
          ./gradlew clean
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
