name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build Setup
        run: |
          npm install -g pnpm
          sed -i '/preinstall/d' package.json
          pnpm config set node-linker hoisted
          pnpm install --no-frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Final Android Fix and Build
        run: |
          # 1. تحديد مكان المجلدات
          ANDROID_DIR=$(find . -path "*/android/gradlew" -printf '%h\n' | head -n 1)
          ROOT_DIR=$(pwd)
          
          cd $ANDROID_DIR
          
          # 2. إعدادات جرادل والمكتبات
          # استخدمنا >> عشان نضيف على الملف بدون ما نمسح أي إعدادات تانية موجودة
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          
          # السطر السحري الجديد عشان نحل مشكلة Reanimated للأبد
          echo "newArchEnabled=true" >> gradle.properties
          
          # مسار الـ node_modules
          echo "nodeModulesPaths=$ROOT_DIR/node_modules" >> gradle.properties

          # 3. تنظيف وبناء
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: "**/build/outputs/apk/release/*.apk"
